server {
    listen 80;
    server_name herihaja.gleeze.com;

    return 301 https://$host$request_uri;
}

server {

    listen 443 ssl;
    server_name herihaja.gleeze.com;

    ssl_certificate /etc/letsencrypt/live/herihaja.gleeze.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/herihaja.gleeze.com/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location = /sitemap.xml {
        access_log /var/log/nginx/sitemap_access.log;
        default_type application/xml;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {

        proxy_pass http://backend:8000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
